import React,{useState} from 'react';
import {NavLink,Link,Outlet,useLocation} from 'react-router-dom';
import {LayoutDashboard,BookOpen,Layers,ClipboardCheck,ChartNoAxesColumn,Library,GraduationCap,Menu,X,ArrowUpRight,AlertCircle,ArrowRight} from 'lucide-react';
import {useStudy} from '../app/Store';
const links=[{to:'/',name:'Dashboard',icon:LayoutDashboard},{to:'/subjects',name:'Subjects',icon:Library},{to:'/study',name:'Reviewer',icon:BookOpen},{to:'/flashcards',name:'Flashcards',icon:Layers},{to:'/exams',name:'Exams',icon:ClipboardCheck},{to:'/progress',name:'Progress',icon:ChartNoAxesColumn}];
export function Logo(){return <Link className="brand" to="/"><span className="brand-mark"><GraduationCap size={19}/></span><span>studyspace<span className="brand-period">.</span></span></Link>}
export function Shell(){const [open,setOpen]=useState(false);const location=useLocation();const {warning,clearWarning,session}=useStudy();return <div className="app-shell">
 <aside className={'sidebar '+(open?'is-open':'')}><div className="sidebar-header"><Logo/><button className="icon-btn close-mobile" onClick={()=>setOpen(false)} aria-label="Close menu"><X size={20}/></button></div><div className="sidebar-caption">WORKSPACE</div><nav className="sidebar-nav" aria-label="Main navigation">{links.map(({to,name,icon:Icon})=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>'sidebar-link '+(isActive||(to==='/study'&&location.pathname.startsWith('/study/'))?'active':'')}><Icon size={18} strokeWidth={1.9}/><span>{name}</span></NavLink>)}</nav><div className="sidebar-lower"><div className="sidebar-note"><div className="note-icon"><BookOpen size={17}/></div><strong>Learn at your pace</strong><p>Your progress stays in this browser. No account needed.</p></div><span className="version">STUDYSPACE / VERSION 1.0</span></div></aside>
 {open&&<button className="sidebar-backdrop" onClick={()=>setOpen(false)} aria-label="Close navigation"/>}
 <div className="app-main"><header className="topbar"><div className="topbar-left"><button className="icon-btn menu-mobile" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={21}/></button><span className="breadcrumb">YOUR WORKSPACE <span className="slash">/</span> {links.find(x=>x.to===location.pathname)?.name.toUpperCase()??'LEARNING'}</span></div><div className="topbar-right"><span className="topbar-status"><span className="green-dot"/>Local study mode</span>{session&&<Link className="topbar-resume" to={'/exam/'+session.id}>Resume exam <ArrowUpRight size={15}/></Link>}</div></header>{warning&&<div className="alert-bar" role="alert"><AlertCircle size={17}/><span>{warning}</span><button onClick={clearWarning} aria-label="Dismiss warning"><X size={16}/></button></div>}<main className="page-wrap"><Outlet/></main><footer className="site-footer"><span>Made for focused study. No accounts, no distractions.</span><span>StudySpace © 2026</span></footer></div></div>}
export function PageHeading({eyebrow,title,subtitle,aside}:{eyebrow:string;title:string;subtitle?:string;aside?:React.ReactNode}){return <header className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{aside&&<div className="page-heading-aside">{aside}</div>}</header>}
export function PrimaryLink({to,children,ghost=false}:{to:string;children:React.ReactNode;ghost?:boolean}){return <Link to={to} className={ghost?'btn btn-secondary':'btn btn-primary'}>{children}<ArrowRight size={16}/></Link>}
export function EmptyState({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="empty-state"><div className="empty-illustration"><Layers size={26}/></div><h3>{title}</h3><p>{description}</p>{action}</div>}
